### ISSUE TITLE
Tests require newer Test::Moose::More

### ISSUE THREAD

**Issue by dmaestro** [drzigman/WWW-LogicBoxes#3]
Version 0.29 changed the api for some test methods, including `is_role_ok`. Prior versions don't work with your tests and the module fails to install with `cpanm`.

Stopgap measure is to require this version in the test scripts; but I can see problems if people can't/won't upgrade because they have their own test code using the old api :-(

**Comment by drzigman** [comment]
Thanks!

PR #4 has been merged.
